scene_dirpath: ./datasets/matrixcity/aerial/train/block_all
output_dirpath: ./output/mc_aerial_vq
white_background: false
sh_degree: 3
evaluate: True
scene_scale: 1.0
image_scale: 0.5
expand_ratio: 0.05
vertical_axis: "z"
max_tree_depth: 6
num_points_thresh: 300000
cover_ratio_thresh: 0.3

num_workers: 0
batch_size: 1
preload: "cpu"
iterations: 40000

position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: None
feature_lr: 0.0025
opacity_lr: 0.025
scaling_lr: 0.005
rotation_lr: 0.001
random_background: false

lambda_dssim: 0.2
depth_l1_weight_init: 1.0
depth_l1_weight_final: 0.1
reproj_l1_weight_init: 0.01
reproj_l1_weight_final: 0.5
depth_inv_loss: true
pesudo_loss: true
pesudo_loss_start: 5000

percent_dense: 0.01
densify_grad_threshold: 0.0002
densification_interval: 500
densify_from_iter: 1000
densify_until_iter: 20000
opacity_reset_interval: 20000
min_opacity: 0.005
densify_only_in_block: true

convert_SHs_python: false
compute_cov3D_python: false
debug: false
antialiasing: false

quant_params: ['sh', 'dc']
rvq_layers: 2
vq_mode: 'online'

kmeans_st_iter: 20000
kmeans_freq: 100

kmeans_ncls_sh: 1024
kmeans_ncls_dc: 512
kmeans_iters: 5

sh_band_weighting: true
band_weight_alpha: 0.15
layer_aware_training: true

use_index_prior: false