# VQ Fast Mode Configuration - K-Means equivalent (rvq_layers=1)
# 快速模式配置 - 相当于传统K-Means，训练速度最快

# scene params
scene_dirpath: ./datasets/matrixcity/aerial/train/block_all
output_dirpath: ./output/mc_aerial_vq_fast
white_background: false
sh_degree: 3
evaluate: false
scene_scale: 1.0
image_scale: 0.5
expand_ratio: 0.05
vertical_axis: "z"
max_tree_depth: 6
num_points_thresh: 300000
cover_ratio_thresh: 0.3

# training params
num_workers: 0
batch_size: 1
preload: "cpu"
iterations: 15000  # 稍微减少迭代次数

position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: None
feature_lr: 0.0025
opacity_lr: 0.025
scaling_lr: 0.005
rotation_lr: 0.001
random_background: false

lambda_dssim: 0.2
depth_l1_weight_init: 1.0
depth_l1_weight_final: 0.1
reproj_l1_weight_init: 0.01
reproj_l1_weight_final: 0.5
depth_inv_loss: true
pesudo_loss: true
pesudo_loss_start: 3000

# densify and prune params
percent_dense: 0.01
densify_grad_threshold: 0.0002
densification_interval: 500
densify_from_iter: 1000
densify_until_iter: 15000
opacity_reset_interval: 15000
min_opacity: 0.005
densify_only_in_block: true

# rendering params
convert_SHs_python: false
compute_cov3D_python: false
debug: false
antialiasing: false

# VQ parameters - Fast Mode (K-Means equivalent)
quant_params: ['sh', 'dc']
rvq_layers: 1                   # 单层 = K-Means等价，最快速度
vq_mode: 'online'
kmeans_st_iter: 8000            # 更早开始VQ
kmeans_freq: 200                # 较低频率减少计算
kmeans_ncls_sh: 256             # 较少聚类数，更快速度
kmeans_ncls_dc: 2048            # 较少聚类数，更快速度
kmeans_iters: 8                 # 较少迭代次数
# kmeans_max_samples removed - uses full data for better initialization 